<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>906aa9a7-cded-43a7-bf63-a334e1699b2e</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebArMa.ArMaMelk.API.Application\WebArMa.ArMaMelk.API.Application.csproj" />
		<ProjectReference Include="..\WebArMa.ArMaMelk.API.Infrastructure\WebArMa.ArMaMelk.API.Infrastructure.csproj" />
		<ProjectReference Include="..\WebArMa.ArMaMelk.Persistence\WebArMa.ArMaMelk.Persistence.csproj" />
	</ItemGroup>

</Project>
