using Mediator;
using WebArMa.ArMaMelk.API.Domain.RealEstates.Enums;

namespace WebArMa.ArMaMelk.API.Application.Units.Commands.Update
{
    public record UpdateCommand(
        Guid Guid,
        string Title,
        RealEstateType RealEstateType,
        UsageType UsageType,
        int VillageId,
        string SystemAddress,
        string AddressLine,
        decimal Area,
        decimal? LandArea,
        int? Rooms,
        int? Bedrooms,
        int? Floor,
        int? TotalFloors,
        int? RealEstateCount,
        int? RealEstatePerFloor,
        int? YearBuilt,
        bool HasParking,
        int? ParkingCount,
        bool HasStorage,
        decimal? StorageArea,
        bool HasElevator,
        bool HasBalcony,
        bool HasTerrace,
        bool HasYard,
        bool HasPool,
        bool HasSauna,
        bool HasJacuzzi,
        bool HasSecurity,
        bool HasCCTV,
        Guid PersonGuid,
        RealEstateDocumentType DocumentType,
        RealEstateDocumentStatus DocumentStatus,
        RealEstateOwnershipType OwnershipType,
        int? BuildingTotalFloors = null,
        int? BuildingRealEstateCount = null,
        int? BuildingRealEstatePerFloor = null,
        ConstructionType? ConstructionType = null,
        FacadeType? FacadeType = null) : IRequest;
}
